# Generated by Django 4.1 on 2022-09-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_document_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='time',
            new_name='time_uploaded',
        ),
    ]
