# Generated by Django 4.1 on 2022-09-12 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_document_date_uploaded_alter_document_time_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_document',
            name='path',
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
