# Generated by Django 4.1 on 2022-09-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_alter_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pdf',
        ),
    ]
